Warm up1
EKrysenko/Slaries-practice pull request #6
Opened 2019-06-30 18:54 UTC by Slaries

серия задач решены

2019-06-30 20:27 UTC, EKrysenko commented on src/main/java/warmup/WarmUp1.java
> +        if (aValue != bValue){
Решение норм.
Почитай про XOR (исключающее "или"), и сделай это решение охуенным)

2019-06-30 20:30 UTC, EKrysenko commented on src/main/java/warmup/WarmUp1.java
> +        }else{
На самом деле, в случае, если в теле ифа у тебя return, то else избыточен. 
```
if (условие соблюдается) {
    return что-то. (всё, в этом случае мы никак не окажемся ещё и в следующем блоке)
} 
return что-то другое
```

2019-06-30 20:32 UTC, EKrysenko commented on src/main/java/warmup/WarmUp1.java
> +        }
чё за пустой else?

2019-06-30 20:34 UTC, EKrysenko commented on src/main/java/warmup/WarmUp1.java
> +            return true;
весь этот if - else можно заменить на единственный return. подумай, какой.

2019-06-30 20:36 UTC, EKrysenko requested changes

2019-06-30 20:36 UTC, EKrysenko commented on src/main/java/warmup/WarmUp1.java
> +            return true;
весь этот if - else можно заменить на единственный return. подумай, какой.

2019-06-30 20:36 UTC, EKrysenko commented on src/main/java/warmup/WarmUp1.java
> +        }else {
чё за пустой else?

2019-07-01 08:41 UTC, EKrysenko requested changes

2019-07-01 08:41 UTC, EKrysenko commented on src/main/java/warmup/WarmUp1.java
> +    for (int i = 0; i<a; i++){
Это прям плохое решение. 
Тебе нужно по условию рассмотреть char`ы в позиции от 1 до 3. Ты идёшь циклом через всю строку. 
Представь, что у тебя строка в 1000 символов, и таких строк тысяча. вместо трёх тысяч проверок ( по три на каждую входящую строку) ты выполнишь миллион операций. Чувствуешь разницу?

Я предлагаю тебе рассмотреть два варианта решения. 
1. Исправить твоё решение так, чтобы не идти циклом по всей строке, а только в нужной части.
2. Из строки взять подстроку от 1 до 3 символов и воспользоваться методом contains() в классе String.

2019-07-01 08:41 UTC, EKrysenko commented on src/main/java/warmup/WarmUp1.java
> +        result += str.charAt(i);
В целом это годное решение. 
Но есть вещь, которую тебе нужно знать. 
Класс String в джава иммутабельный. Это означает, что объекты (инстансы) этого класса неизменяемы. 
И это, в свою очередь, означает, что каждый раз, когда ты пишешь "строка + другая строка или чар" - ты плодишь новую строку. Выполнишь тысячу раз - создашь тысячу новых строк. А память у нас не резиновая, тебе ли не знать. 
Предлагаю почитать про класс StringBuilder и попробовать реализовать этот метод с использованием этого класса.

2019-07-01 08:41 UTC, EKrysenko commented on src/main/java/warmup/WarmUp1.java
> +        }else {
Ещё раз. Что за пустой else?

2019-07-01 08:41 UTC, EKrysenko commented on src/main/java/warmup/WarmUp1.java
> +            return true;
Мы это уже проходили. Твой метод возвращает булевый результат. И иф тоже возвращает булевый результат. 
Весь этот иф-элс можно заменить на однострочный return.

2019-07-01 14:28 UTC, Slaries reviewed
класс StringBuilder в задаче everyNTH использована

2019-07-01 14:28 UTC, Slaries commented on src/main/java/warmup/WarmUp1.java
> +        }else {
убрано лишнее

2019-07-01 14:28 UTC, Slaries commented on src/main/java/warmup/WarmUp1.java
> +            return true;
решено в одну строку

2019-07-01 14:31 UTC, Slaries commented on src/main/java/warmup/WarmUp1.java
> +        result += str.charAt(i);
Класс StringBuilder использован успешно!

2019-07-01 16:42 UTC, merged